tinyMCE.addI18n('hu.advimage_dlg',{
"image_list":"Képlista",
"align_right":"Jobbra",
"align_left":"Balra",
"align_textbottom":"Szöveg alja",
"align_texttop":"Szöveg teteje",
"align_bottom":"Lent",
"align_middle":"Középen",
"align_top":"Fent",
"align_baseline":"Alapvonal",
align:"Igazítás",
hspace:"Vízszintes térköz",
vspace:"Függőleges térköz",
dimensions:"Méretek",
border:"Keret",
list:"Képlista",
alt:"Képleírás",
src:"Kép URL",
"dialog_title":"Kép beszúrása/szerkesztése",
"missing_alt":"Biztosan nem szükséges a képleírás? Enélkül a kép egyes képességhiányos személyeknek, a szöveges böngészőt használóknak vagy a képet nem használó böngészők esetén nem lesz elérhető.",
"example_img":"Kép előnézet megjelenés",
misc:"Egyéb",
mouseout:"Nem egér alatt",
mouseover:"Egér alatt",
"alt_image":"Alternatív kép",
"swap_image":"Képcsere",
map:"Képtérkép",
id:"AZ",
rtl:"Jobbról balra",
ltr:"Balról jobbra",
classes:"Osztályok",
style:"Stílus",
"long_desc":"Hosszú leírás link",
langcode:"Nyelvkód",
langdir:"Nyelvirány",
"constrain_proportions":"Arányok megtartása",
preview:"Előnézet",
title:"Cím",
general:"Általános",
"tab_advanced":"Bővített",
"tab_appearance":"Megjelenés",
"tab_general":"Általános",
width:"Szélesség",
height:"Magasság"
});