tinyMCE.addI18n('hu.media_dlg',{
list:"Lista",
file:"Fájl/URL",
advanced:"Bővített",
general:"Általános",
title:"Beágyazott média beszúrása/szerkesztése",
"align_top_left":"Balra fent",
"align_center":"Középen",
"align_left":"Balra",
"align_bottom":"Lent",
"align_right":"Jobbra",
"align_top":"Fent",
"qt_stream_warn":"A folyamszerű rtsp forrásokat a QT Src mezőhöz kell adni a Bővített fülnél.\nAdhatunk nem-folyamszerű verziót is az Src mezőhöz.",
qtsrc:"QT forrás",
progress:"Feldolgozás",
sound:"Hang",
swstretchvalign:"F-igazítás nyújtás",
swstretchhalign:"V-igazítás nyújtás",
swstretchstyle:"Nyújtás stílus",
scriptcallbacks:"Szkript visszahívások",
"align_top_right":"Jobbra fent",
uimode:"UI müd",
rate:"Ráta",
playcount:"Lejátszás számlálás",
defaultframe:"Alapértelmezett keret",
currentposition:"Aktuális pozíció",
currentmarker:"Aktuális jelölő",
captioningid:"Képealáírási azonosító",
baseurl:"Alap URL",
balance:"Egyensúly",
windowlessvideo:"Ablak nélküli videó",
stretchtofit:"Méretre nyújtás",
mute:"Csend",
invokeurls:"URL-k beiktatása",
fullscreen:"Teljes képernyő",
enabled:"Engedélyezve",
autostart:"Automatikus indítás",
volume:"Hangerő",
target:"Cél",
qtsrcchokespeed:"Betöltési sebesség",
href:"HREF",
endtime:"Befejezési idő",
starttime:"Kezdési idő",
enablejavascript:"JavaScript engedélyezése",
correction:"Nincs javítás",
targetcache:"Cél gyorsítótár",
playeveryframe:"Minden keret lejátszása",
kioskmode:"Kioszk mód",
controller:"Vezérlő",
menu:"Menü megjelenítése",
loop:"Hurok",
play:"Automatikus lejátszás",
hspace:"V-térköz",
vspace:"F-térköz",
"class_name":"Osztály",
name:"Név",
id:"AZ",
type:"Típus",
size:"Méretek",
preview:"Előnézet",
"constrain_proportions":"Arányok megtartása",
controls:"Vezérlők",
numloop:"Hurkok száma",
console:"Konzol",
cache:"Gyorsítótár",
autohref:"Automatikus HREF",
liveconnect:"SWLiveConnect",
flashvars:"Flash változók",
base:"Alap",
bgcolor:"Háttér",
wmode:"WMode",
salign:"SIgazítás",
align:"Igazítás",
scale:"Méretarány",
quality:"Minőség",
shuffle:"Keverés",
prefetch:"Előtöltés",
nojava:"Nincs Java",
maintainaspect:"Arány megtartása",
imagestatus:"Képállapot",
center:"Középen",
autogotourl:"Automatikus ugrás URL",
"shockwave_options":"Shockwave opciók",
"rmp_options":"Real Media Player opciók",
"wmp_options":"Windows Media Player opciók",
"qt_options":"QuickTime opciók",
"flash_options":"Flash opciók",
hidden:"Rejtett",
"align_bottom_left":"Balra lent",
"align_bottom_right":"Jobbra lent",
"html5_video_options":"HTML5 videü opciók",
altsource1:"Alternatív forrás #1",
altsource2:"Alternatív forrás #2",
preload:"Előtöltés",
poster:"Poster",
source:"Forrás",
"html5_audio_options":"Audio opciók",
"preload_none":"Nince előtöltés",
"preload_metadata":"Video metaadatok előtöltése",
"preload_auto":"A böngésző dönti el",
 "embedded_audio_options":"Beágyazott audió opciók",
 video:"HTML5 videó",
 audio:"HTML5 audió",
 flash:"Flash",
 quicktime:"QuickTime",
 shockwave:"Shockwave",
 windowsmedia:"Windows Media",
 realmedia:"Real Media",
 iframe:"Iframe",
 embeddedaudio:"Beágyazott audió"
}); 
