tinyMCE.addI18n('hu.table_dlg',{
"rules_border":"border",
"rules_box":"box",
"rules_vsides":"vsides",
"rules_rhs":"rhs",
"rules_lhs":"lhs",
"rules_hsides":"hsides",
"rules_below":"below",
"rules_above":"above",
"rules_void":"void",
rules:"Szabályok",
"frame_all":"all",
"frame_cols":"cols",
"frame_rows":"rows",
"frame_groups":"groups",
"frame_none":"none",
frame:"Keret",
caption:"Táblázataláírás",
"missing_scope":"Biztosan folytatjuk a táblázat fejléc cella hatókörének megadása nélkül. Enélkül bizonyos rokkant felhasználók részére problémák jelentkezhetnek a tartalom megértésében vagy a táblázat adatainak megjelenítésében.",
"cell_limit":"Túlléptük a cellák maximális számát: cells of {$cells}.",
"row_limit":"Túlléptük a sorok maximális számát: {$rows}.",
"col_limit":"Túlléptük a oszlopok maximális számát: {$cols}.",
colgroup:"Oszlopcsoport",
rowgroup:"Sorcsoport",
scope:"Hatókör",
tfoot:"Lábléc",
tbody:"Törzs",
thead:"Fejlc",
"row_all":"Összes sor frissítése a táblázatban",
"row_even":"A táblázat páros sorainak frissítése",
"row_odd":"A táblázat páratlan sorainak frissítése",
"row_row":"Aktuális sor frissítése",
"cell_all":"Összes cella frissítése a táblázatban",
"cell_row":"Összes cella frissítése a sorban",
"cell_cell":"Aktuális cella frissítése",
th:"Fejléc",
td:"Adatok",
summary:"Összegzés",
bgimage:"Háttérkép",
rtl:"Jobbról balra",
ltr:"Balról jobbra",
mime:"Cél MIME típus",
langcode:"Nyelvkód",
langdir:"Nyelvirány",
style:"Stílus",
id:"AZ",
"merge_cells_title":"Táblázatcellák összevonása",
bgcolor:"Háttérszín",
bordercolor:"Keretszín",
"align_bottom":"Lent",
"align_top":"Fent",
valign:"Függőleges igazítás",
"cell_type":"Cellatípus",
"cell_title":"Táblacella tulajdonságok",
"row_title":"Táblasor tulajdonságok",
"align_middle":"Középre",
"align_right":"Jobbra",
"align_left":"Balra",
"align_default":"Alapértelmezett",
align:"Igazítás",
border:"Keret",
cellpadding:"Cellamargó",
cellspacing:"Cellatérköz",
rows:"Sorok",
cols:"Oszlopok",
height:"Magasság",
width:"Szélesség",
title:"Táblázat beszúrása/szerkesztése",
rowtype:"Sortípus",
"advanced_props":"Bővített beállítások",
"general_props":"Általános bellítások",
"advanced_tab":"Bővített",
"general_tab":"Általános",
"cell_col":"Összes cella frissítése az oszlopban"
});