tinyMCE.addI18n('hu.style_dlg',{
"text_lineheight":"Sormagasság",
"text_variant":"Változat",
"text_style":"Stílus",
"text_weight":"Súly",
"text_size":"Méret",
"text_font":"Betű",
"text_props":"Szöveg",
"positioning_tab":"Pozícionálás",
"list_tab":"Lista",
"border_tab":"Keret",
"box_tab":"Doboz",
"block_tab":"Blokk",
"background_tab":"Háttér",
"text_tab":"Szöveg",
apply:"Alkalmazás",
title:"CSS stílus szerkesztése",
clip:"Klipp",
placement:"Elhelyezés",
overflow:"Átfedés",
zindex:"Z-index",
visibility:"Láthatóság",
"positioning_type":"Típus",
position:"Pozíció",
"bullet_image":"Bajúszkép",
"list_type":"Típus",
color:"Szín",
height:"Magasság",
width:"Szélesség",
style:"Stílus",
margin:"Külső margó",
left:"Balra",
bottom:"Lent,
right:"Jobbra",
top:"Fent",
same:"Ugyanaz mindegyiknél",
padding:"Belső margó",
"box_clear":"Tiszta",
"box_float":"Úsztatás",
"box_height":"Magasság",
"box_width":"Szélesség",
"block_display":"Megjelenítés",
"block_whitespace":"Fehér szóköz",
"block_text_indent":"Szövegbehúzás",
"block_text_align":"Szövegigazítás",
"block_vertical_alignment":"Függőleges igazítás",
"block_letterspacing":"Betűtávolság",
"block_wordspacing":"Szótávolság",
"background_vpos":"Függőleges pozíció",
"background_hpos":"Vízszintes pozíció",
"background_attachment":"Csatolás",
"background_repeat":"Ismétlés",
"background_image":"Háttérkép",
"background_color":"Háttérszín",
"text_none":"Nincs",
"text_blink":"Villogás",
"text_case":"Betűállás",
"text_striketrough":"Áthúzott",
"text_underline":"Aláhúzott",
"text_overline":"Föléhízott",
"text_decoration":"Dekoráció",
"text_color":"Szín",
text:"Szöveg",
background:"Háttér",
block:"Blokk",
box:"Doboz",
border:"Keret",
list:"Lista"
});