tinyMCE.addI18n('hu.fullpage_dlg',{
title:"Dokumentum tulajdonságok",
"meta_tab":"Általános",
"appearance_tab":"Megjelenés",
"advanced_tab":"Bővített",
"meta_props":"Metainformáció",
langprops:"Nyelv és kódolás",
"meta_title":"Cím",
"meta_keywords":"Kulcsszavak",
"meta_description":"Leírás",
"meta_robots":"Robotok",
doctypes:"Doctype",
langcode:"Nyelvkód",
langdir:"Nyelvirány",
ltr:"Balról jobbra",
rtl:"Jobbról balra",
"xml_pi":"XML deklaráció",
encoding:"Karakter-kódolás",
"appearance_bgprops":"Háttér tulajdonságok",
"appearance_marginprops":"Törzsmargók",
"appearance_linkprops":"Linkszínek",
"appearance_textprops":"Szöveg tulajdonságok",
bgcolor:"Háttérszín",
bgimage:"Háttérkép",
"left_margin":"Bal margó",
"right_margin":"Jobb margó",
"top_margin":"Felső margó",
"bottom_margin":"Alsó margó",
"text_color":"Szövegszín",
"font_size":"Betűméret",
"font_face":"Betűforma",
"link_color":"Linkszín",
"hover_color":"Egér alatti linkszín",
"visited_color":"Látogatott linkszín",
"active_color":"Aktív linkszín",
textcolor:"Szín",
fontsize:"Betűméret",
fontface:"Betűcsalád",
"meta_index_follow":"Linkek indexelése és követése",
"meta_index_nofollow":"Linkek indexelése de nem követése",
"meta_noindex_follow":"Linkek követése de nem indexelése",
"meta_noindex_nofollow":"Linkek se nem indexelése, se nem követése",
"appearance_style":"Stíluslap és stílustulajdonságok",
stylesheet:"Stíluslap",
style:"Stílus",
author:"Szerző",
copyright:"Copyright",
add:"Új elem hozzáadása",
remove:"Kiválasztott elem eltávolítása",
moveup:"Kiválasztott elem fel",
movedown:"Kiválasztott elem le",
"head_elements":"Fejléc elemek",
info:"Információ",
"add_title":"Címelem",
"add_meta":"Metaelem",
"add_script":"Szkriptelem",
"add_style":"Stíluselem",
"add_link":"Linkelem",
"add_base":"Alapelem",
"add_comment":"Hozzászólás elem",
"title_element":"Címelem",
"script_element":"Szkriptelem",
"style_element":"Stíluselem",
"base_element":"Alapelem",
"link_element":"Linkelem",
"meta_element":"Metaelem",
"comment_element":"Hozzászólás",
src:"Forrás",
language:"Nyelv",
href:"HREF",
target:"Cél",
type:"Típus",
charset:"Karakterkészlet",
defer:"Defer",
media:"Media",
properties:"Tulajdonságok",
name:"Név",
value:"Érték",
content:"Tartalom",
rel:"Rel",
rev:"Rev",
hreflang:"HREF nyelv",
"general_props":"Általános",
"advanced_props":"Bővített"
});