tinyMCE.addI18n('hu.advlink_dlg',{
"target_name":"Célnév",
classes:"Osztályok",
style:"Stílus",
id:"AZ",
"popup_position":"Pozíció (X/Y)",
langdir:"Nyelvirány",
"popup_size":"Méret",
"popup_dependent":"Függőség (csak Mozilla/Firefox)",
"popup_resizable":"Átméretezhető ablak",
"popup_location":"Helysáv megjelenítése",
"popup_menubar":"Menüsáv megjelenítése",
"popup_toolbar":"Eszköztárak megjelenítése",
"popup_statusbar":"Állapotsáv megjelenítése",
"popup_scrollbars":"Gördítősávok megjelenítése",
"popup_return":"\'return false\' beszúrása",
"popup_name":"Ablaknév",
"popup_url":"Felbukkanú ablak URL",
popup:"JavaScript felbukkanó ablak",
"target_blank":"Megnyitás új ablakban",
"target_top":"Megnyitás legfelső keretben (összes keret lecserélése)",
"target_parent":"Megnyitás szülő ablakban/keretben",
"target_same":"Megnyitás azonos ablakban/keretben",
"anchor_names":"Horgonyok",
"popup_opts":"Opciók",
"advanced_props":"Bővített tuldjdpnságok",
"event_props":"Események",
"popup_props":"Felbukkanó ablak tulajdonságok",
"general_props":"Általános tulajdonságok",
"advanced_tab":"Bővített",
"events_tab":"Események",
"popup_tab":"Felbukkanó ablak",
"general_tab":"Általános",
list:"Linklista",
"is_external":"A megadott URL külső URL-nek tűnik. Ki legyen egészítve a kötelező http:// előtaggal?",
"is_email":"A megadott URL email címnek tűnik. Ki legyen egészítve a kötelező mailto előtaggal?",
titlefield:"Cím",
target:"Cél",
url:"Link URL",
title:"Link beszúrása/szerkesztése",
"link_list":"Linklista",
rtl:"Jobbról balra",
ltr:"Balról jobbra",
accesskey:"Eléréskulcs",
tabindex:"Tabulációs index",
rev:"Cél-oldal kapcsolat",
rel:"Oldal-cél kapcsolat",
mime:"Cél MIME típus",
encoding:"Cél karakterkódolás",
langcode:"Nyelvkód",
"target_langcode":"Célnyelv",
width:"Szélesség",
height:"Magasság"
});