tinyMCE.addI18n('hu.advanced',{
"underline_desc":"Aláhúzott (Ctrl+U)",
"italic_desc":"Dőlt (Ctrl+I)",
"bold_desc":"Félkövér (Ctrl+B)",
dd:"Definíció leírás",
dt:"Definíció meghatározás ",
samp:"Kódpélda",
code:"Kód",
blockquote:"Blokkidézet",
h6:"Címsor #6",
h5:"Címsor #5",
h4:"Címsor #4",
h3:"Címsor #3",
h2:"Címsor #2",
h1:"Címsor #1",
pre:"Előformázott",
address:"Cím",
div:"DIV",
paragraph:"Bekezdés",
block:"Formázás",
fontdefault:"Betűcsalád",
"font_size":"Betűméret",
"style_select":"Stílusok",
"anchor_delta_height":"",
"anchor_delta_width":"",
"charmap_delta_height":"",
"charmap_delta_width":"",
"colorpicker_delta_height":"",
"colorpicker_delta_width":"",
"link_delta_height":"",
"link_delta_width":"",
"image_delta_height":"",
"image_delta_width":"",
"more_colors":"További színek...",
"toolbar_focus":"Ugrás az eszközgombokhoz - Alt+Q, Ugrás a szövegszerkesztőhöz - Alt-Z, Ugrás az elemútvonalhoz - Alt-X",
newdocument:"Biztosan tölésre kerüljön az összes tartalom?",
path:"Útvonal",
"clipboard_msg":"A másolás/kivágás/beszúrás nem használható a Mozilla és Firefox böngészőkben.\nTovábbi információ?",
"blockquote_desc":"Blokkidézet",
"help_desc":"Súgó",
"newdocument_desc":"Új dokumentum",
"image_props_desc":"Kép tulajdonásgok",
"paste_desc":"Beszúrás (Ctrl+V)",
"copy_desc":"Másolás (Ctrl+C)",
"cut_desc":"Kivágás (Ctrl+X)",
"anchor_desc":"Horgony beszúrása/szerkesztése",
"visualaid_desc":"Vezérlővonalak/láthatatlan elemek megjelenítése/elrejtése",
"charmap_desc":"Speciális karakter beszúrása",
"backcolor_desc":"Háttérszín kiválasztása",
"forecolor_desc":"Szövegszín kiválasztása",
"custom1_desc":"Egyedi leírás kerül ide",
"removeformat_desc":"Formázás eltávolítása",
"hr_desc":"Vízszintes vonal beszúrása",
"sup_desc":"Felső index",
"sub_desc":"Alsó index",
"code_desc":"HTML forrás szerkesztése",
"cleanup_desc":"Kód tisztítás",
"image_desc":"Kép beszúrása/szerkesztése",
"unlink_desc":"Link eltávolítása",
"link_desc":"Link beszúrása/szerkesztése",
"redo_desc":"Mégis (Ctrl+Y)",
"undo_desc":"Mégsem (Ctrl+Z)",
"indent_desc":"Behúzás növelése",
"outdent_desc":"Behúzás csökkentése",
"numlist_desc":"Számozott lista beszúrása/eltávolítása",
"bullist_desc":"Felsorolásos lista beszúrása/eltávolítása",
"justifyfull_desc":"Sorkizárt igazítás",
"justifyright_desc":"Jobbra igazítás",
"justifycenter_desc":"Középre igazítás",
"justifyleft_desc":"Balra igazítás",
"striketrough_desc":"Áthúzott",
"help_shortcut":"ALT-F10 - eszköztár. ALT-0 - súgó",
"rich_text_area":"Fejlett szövegszekesztő terület",
"shortcuts_desc":"Elérhetőségi súgó",
toolbar:"Eszköztár"});