tinyMCE.addI18n('hu.advanced_dlg', {
"link_list":"Linklista",
"link_is_external":"A megadott URL külső URL-nek tűnik. Ki legyen egészítve a kötelező http:// előtaggal?",
"link_is_email":"A megadott URL email címnek tűnik. Ki legyen egészítve a kötelező mailto előtaggal?",
"link_titlefield":"Cím",
"link_target_blank":"Link megnyitása új ablakban",
"link_target_same":"Link megnyitása ugyanabban az ablakban",
"link_target":"Cél",
"link_url":"Link URL",
"link_title":"Link beszúrása/szerkesztése",
"image_align_right":"Jobbra",
"image_align_left":"Balra",
"image_align_textbottom":"Szöveg alja",
"image_align_texttop":"Szöveg teteje",
"image_align_bottom":"Lent",
"image_align_middle":"Középen",
"image_align_top":"Fent",
"image_align_baseline":"Alapvonal",
"image_align":"Igazítás",
"image_hspace":"Vízszintes térköz",
"image_vspace":"Függőleges térköz",
"image_dimensions":"Méretek",
"image_alt":"Képleírás",
"image_list":"Képlista",
"image_border":"Keret",
"image_src":"Kép URL",
"image_title":"Kép beszúrása/szerkesztése",
"charmap_title":"Speciális karakter kiválasztása",
 "charmap_usage":"Navigáció: balra nyíl és jobbra nyíl.",
"colorpicker_name":"Név:",
"colorpicker_color":"Szín:",
"colorpicker_named_title":"Elnevezett színek",
"colorpicker_named_tab":"Elnevezett",
"colorpicker_palette_title":"Színpaletta",
"colorpicker_palette_tab":"Paletta",
"colorpicker_picker_title":"Színpipetta",
"colorpicker_picker_tab":"Pipetta",
"colorpicker_title":"Színválasztás",
"code_wordwrap":"Szótördelés",
"code_title":"HTML forrásszerkesztő",
"anchor_name":"Horgonynév",
"anchor_title":"Horgony beszúrása/szerkesztése",
"about_loaded":"Betöltött beépülők",
"about_version":"Verzió",
"about_author":"Szerző",
"about_plugin":"Beépülő",
"about_plugins":"Beépülők",
"about_license":"Licensz",
"about_help":"Súgó",
"about_general":"Névjegy",
"about_title":"TinyMCE névjegy",
"anchor_invalid":"Érvényes horgonynevet kell megadni.",
"accessibility_help":"Elérhetőségi súgó",
"accessibility_usage_title":"Általános használat",
"":""
});
