<?php
defined( '_JEXEC' ) or die( '=;)' );
class felhasznaloiJogok{
	function _(){
			$arr = array(
				"Super Users" => array(
					"hirlevel_cimek","hirlevel_cim",
					"hirlevelek","hirlevel",
					"hirlevel_listak","hirlevel_lista",
					"contents","content",
					"galleries","gallery",
					"atvhelyek","atvhely",
					"wh",
					"keresesek",
					"tetelek,tetel",
					"kimutatas",
					"impex",
					"kuponok","kupon",
					"fcsoportok,fcsoport",
					"felhasznalok,felhasznalo",
					"rendelesek,rendeles",
					"kampanyok,kampany",
					"termekek,termek,kepek,kep",
					"kategoriak,kategoria",
					"beszallitok,beszallito",
					"webshopok,webshop",
					"gyartok,gyarto",
					"msablonok,msablon",
					"msablon_mezok,msablon_mezo",
					"arlekeres",
					"linkek",
					"beallitas",
					"szerviz",
					"hirlevel",
				),
				"whadmin" => array(
					"hirlevel_cimek","hirlevel_cim",
					"hirlevelek","hirlevel",
					"hirlevel_listak","hirlevel_lista",
					"contents","content",
					"galleries","gallery",
					"atvhelyek","atvhely",
					"wh",
					"keresesek",
					"tetelek,tetel",
					"kimutatas",
					"impex",
					"kuponok","kupon",
					"fcsoportok,fcsoport",
					"felhasznalok,felhasznalo",
					"rendelesek,rendeles",
					"kampanyok,kampany",
					"termekek,termek,kepek,kep",
					"kategoriak,kategoria",
					"beszallitok,beszallito",
					"webshopok,webshop",
					"gyartok,gyarto",
					"msablonok,msablon",
					"msablon_mezok,msablon_mezo",
					"arlekeres",
					"linkek",
					"beallitas",
					"szerviz",
					"hirlevel",
				),
			
				"diszpecser"=>array(
					"wh",
					"szemafor",
					//"termekek,termek,kepek,kep",
					//"kategoriak,kategoria",
					//"beszallitok,beszallito",
					//"webshopok,webshop",
					//"gyartok,gyarto",
					//"msablonok,msablon",
					//"msablon_mezok,msablon_mezok",
					//"arlekeres",																															
					//"linkek",
					//"beallitas",
					//"szerviz",
					//"hirlevel",//sajathirleveles program, vodafone
				),
			
				"termekmenedzser"=>array(
					"wh",
					//"rendelesek,rendeles",
					//"tetelek,tetel",
					//"kimutatas",
					"termekek,termek,kepek,kep",
					"kategoriak,kategoria",
					"beszallitok,beszallito",
					"webshopok,webshop",
					"gyartok,gyarto",
					"msablonok,msablon",
					"msablon_mezok,msablon_mezok",
					"arlekeres",																															
					"linkek",
					"beallitas",
					"szerviz",
					"hirlevel",//sajathirleveles program, vodafone
				),
				
				"penzugy"=>array(
					"wh",
					"rendelesek,rendeles",
					"tetelek,tetel",
					"kimutatas",
					//"termekek,termek,kepek,kep",
					//"kategoriak,kategoria",
					//"beszallitok,beszallito",
					//"webshopok,webshop",
					//"gyartok,gyarto",
					//"msablonok,msablon",
					//"msablon_mezok,msablon_mezok",
					//"arlekeres",																															
					//"linkek",
					//"beallitas",
					//"szerviz",
					//"hirlevel",//sajathirleveles program, vodafone
				),
				
				"csomagolas"=>array(
					"wh",
					"rendelesek,rendeles",
					"tetelek,tetel",
					//"kimutatas",
					//"termekek,termek,kepek,kep",
					//"kategoriak,kategoria",
					//"beszallitok,beszallito",
					//"webshopok,webshop",
					//"gyartok,gyarto",
					//"msablonok,msablon",
					//"msablon_mezok,msablon_mezok",
					//"arlekeres",																															
					//"linkek",
					//"beallitas",
					//"szerviz",
					//"hirlevel",//sajathirleveles program, vodafone
				),				

				"csomagolas_termekmenedzser"=>array(
					"wh",
					"rendelesek,rendeles",
					"tetelek,tetel",
					//"kimutatas",
					"termekek,termek,kepek,kep",
					"kategoriak,kategoria",
					"beszallitok,beszallito",
					"webshopok,webshop",
					"gyartok,gyarto",
					"msablonok,msablon",
					"msablon_mezok,msablon_mezok",
					"arlekeres",																															
					"linkek",
					//"beallitas",
					//"szerviz",
					//"hirlevel",//sajathirleveles program, vodafone
				),								

				"vodafone"=>array(
					"wh",
					"rendelesek,rendeles",
					//"tetelek,tetel",
					//"kimutatas",
					//"termekek,termek,kepek,kep",
					//"kategoriak,kategoria",
					//"beszallitok,beszallito",
					//"webshopok,webshop",
					//"gyartok,gyarto",
					//"msablonok,msablon",
					//"msablon_mezok,msablon_mezok",
					//"arlekeres",																															
					//"linkek",
					//"beallitas",
					"szerviz",
					"hirlevel",//sajathirleveles program, vodafone

				),								
			);
		return $arr;
	}
}