tinyMCE.addI18n('hu.xhtmlxtras_dlg',{
"attribs_title":"Attribútumok beszúrása/szerkesztése",
"option_rtl":"Jobbról balra",
"option_ltr":"Balról jobbra",
"insert_date":"Aktuális dátum/időpont beszúrása",
remove:"Eltávolítás",
"title_cite_element":"Idézet elem",
"title_abbr_element":"Rövidítés elem",
"title_acronym_element":"Mozaikszó elem",
"title_del_element":"Törlés elem",
"title_ins_element":"Beszúrás elem",
"fieldset_events_tab":"Elemesemények",
"fieldset_attrib_tab":"Elem attribútumok",
"fieldset_general_tab":"Általános beállítások",
"events_tab":"Események",
"attrib_tab":"Attribútumok",
"general_tab":"Általános",
"attribute_attrib_tab":"Attribútumok",
"attribute_events_tab":"Események",
"attribute_label_accesskey":"Eléréskucs",
"attribute_label_tabindex":"Tabulátorindex",
"attribute_label_langcode":"Nyelv",
"attribute_option_rtl":"Jobbról balra",
"attribute_option_ltr":"Balról jobbra",
"attribute_label_langdir":"Szövegirány",
"attribute_label_datetime":"Dátum/időpont",
"attribute_label_cite":"Idézet",
"attribute_label_style":"Stílus",
"attribute_label_class":"Osztály",
"attribute_label_id":"AZ",
"attribute_label_title":"Cím"
});